# Override all names
nameOverride: ""
fullnameOverride: ""

firefly:
  app_env: local
  db_connection: mysql

mysql:
  enabled: true
  mysqlUser: firefly
  mysqlDatabase: fireflyiii

deployment:
  # Image used for the deployment
  image:
    repository: jc5x/firefly-iii
    tag: latest
    pullPolicy: IfNotPresent
  # Resources, etc, for the deployment pod
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}


# Should not be changed
service:
  type: ClusterIP
  port: 80

persistence:
  # Whether storing persistent data is enabled or not
  enabled: true
  # The maximum size of the persisted data
  accessMode: ReadWriteOnce
  size: 1Gi
  annotations: {}
  # storageClass: default

# Ingress configuration
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ssl-redirect: "true"
  paths:
    - '/'
  hosts:
    - firefly.domain.tld  # host
  tls:
    - secretName: firefly-tls-secret
      hosts:
        - firefly.domain.tld  # host
