{{- $fullName := include "firefly.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "firefly.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "firefly.name" . }}
    helm.sh/chart: {{ include "firefly.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "firefly.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "firefly.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ $fullName }}
        - secretRef:
            name: {{ template "firefly.fullname" . }}-secrets
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql
              key: mysql-password
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        {{ if .Values.persistence.enabled -}}
        volumeMounts:
        - mountPath: "/var/www/firefly-iii/storage/export"
          subPath: export
          name: firefly-iii-pvc
        - mountPath: "/var/www/firefly-iii/storage/upload"
          subPath: upload
          name: firefly-iii-pvc
        {{ end }}
        resources:
          {{- toYaml .Values.deployment.resources | nindent 12 }}
        {{- with .Values.deployment.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.deployment.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
    {{ if .Values.persistence.enabled }}
      volumes:
      - name: firefly-iii-pvc
        persistentVolumeClaim:
          claimName: {{ $fullName }}
    {{ end }}