apiVersion: v1
kind: Secret
metadata:
  name: {{ template "firefly.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "firefly.name" . }}
    helm.sh/chart: {{ include "firefly.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.firefly.appKey }}
  APP_KEY:  {{ .Values.firefly.appKey | b64enc | quote }}
  {{ else }}
  APP_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}