{{- $fullName := include "firefly.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "firefly.name" . }}
    helm.sh/chart: {{ include "firefly.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "firefly.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
